[workspace]
resolver = "2"
members = [
    "fhevm",
    "compiler",
]

# Workspace-wide dependencies and settings can go here
[workspace.package]

[workspace.dependencies]
poulpy-hal = "0.4.0"
poulpy-core = "0.4.0"
poulpy-cpu-ref = "0.1.0"
poulpy-cpu-avx = "0.1.0"
poulpy-schemes = "0.4.0"