[package]
name = "fhevm"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
poulpy-hal = {path = "../../poulpy/poulpy-hal"}
poulpy-core = {path = "../../poulpy/poulpy-core"}
poulpy-backend = {path = "../../poulpy/poulpy-backend"}
poulpy-schemes = {path = "../../poulpy/poulpy-schemes"}
fhe-ram = { path = "../../fhe-ram"}
rand_core = "0.6.4"

[profile.release]
debug = true
