[package]
name = "fhevm"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
sampling = { path = "../../poulpy/sampling"}
fhe-ram = {path = "../../fhe-ram"}
rand_core = "0.9.3"
core = {path = "../../poulpy/core"}
num-bigfloat = "1.7.2"

[profile.release]
debug = true
