[package]
name = "string-match"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler = {path = "./../../compiler", features = ["verbose"]}
rand = "0.9.0"

[workspace]
members = [ 
    "src/guest"
]
