[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = "0.7.4"
poulpy-hal = "0.3.1"
poulpy-core = "0.3.1"
poulpy-backend = "0.3.1"
poulpy-schemes = "0.3.0"
fhe-ram = { path = "../../fhe-ram"}
fhevm = { path = "../fhevm"}
itertools = "0.14.0"

[features]
verbose=[]
